#!/usr/bin/env python3
"""Generate a custom Amiga .info icon for AmigaAI.

Creates an old-style (OS 1.x-3.x compatible) DiskObject icon with
a Claude robot design, 2 bitplanes (4 colors).

Workbench 2/3 palette:
  Pen 0 = grey (background)
  Pen 1 = black (outlines)
  Pen 2 = white (highlights)
  Pen 3 = blue/orange (fill)

Usage: python3 mkicon.py [outfile] [--robot|--bubble]
  --robot  : Claude robot face (default)
  --bubble : Speech bubble with "AI" text
"""

import struct
import sys
import os

# Icon dimensions
WIDTH = 48    # must be multiple of 16
HEIGHT = 44
DEPTH = 2     # 2 bitplanes = 4 colors

# Pen values
GREY  = 0
BLACK = 1
WHITE = 2
BLUE  = 3

# --- Claude Sparkle (✦) ---
# Generated mathematically using astroid curve: |x/a|^p + |y/b|^p <= 1, p=0.5
# This gives the characteristic concave-sided 4-pointed star shape
ROBOT_ART = None  # generated by make_sparkle_grid()


def make_sparkle_grid():
    """Generate Claude sparkle ✦ shape mathematically.

    Uses astroid equation: sqrt(|x|/a) + sqrt(|y|/b) <= 1
    This produces the concave-sided 4-pointed star shape.
    """
    import math
    g = [[GREY] * WIDTH for _ in range(HEIGHT)]

    cx, cy = 23.5, 21.5   # center
    a = 23.0               # horizontal radius (left/right points)
    b = 21.0               # vertical radius (top/bottom points)
    p = 0.55               # exponent (<1 = concave, >0.5 = less extreme concavity)

    # Fill the shape
    for y in range(HEIGHT):
        for x in range(WIDTH):
            dx = abs(x - cx) / a
            dy = abs(y - cy) / b
            if dx == 0 and dy == 0:
                val = 0
            else:
                val = dx**p + dy**p

            if val <= 1.0:
                g[y][x] = BLUE

    # Add outline (black border where shape meets background)
    outline = [[False] * WIDTH for _ in range(HEIGHT)]
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if g[y][x] == BLUE:
                for nx, ny in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
                    if 0 <= nx < WIDTH and 0 <= ny < HEIGHT:
                        if g[ny][nx] == GREY:
                            outline[y][x] = True
                            break
                    else:
                        outline[y][x] = True
                        break
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if outline[y][x]:
                g[y][x] = BLACK

    # Add white highlight: subtle shine on upper portion
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if g[y][x] == BLUE:
                dx = (x - cx) / a
                dy = (y - cy) / b
                # Highlight along upper center spine
                if dy < -0.05 and abs(dx) < 0.12 and dy > -0.75:
                    g[y][x] = WHITE
                # Small specular highlight upper-left
                if -0.35 < dy < -0.15 and -0.2 < dx < -0.05:
                    g[y][x] = WHITE

    return g

# --- Speech bubble "AI" pixel art (original design, kept as option) ---
BUBBLE_ART = None  # will be generated by make_bubble_grid()


def make_bubble_grid():
    """Create the speech bubble + AI text pixel grid (original design)."""
    g = [[GREY] * WIDTH for _ in range(HEIGHT)]

    def fill_rounded_rect(g, x1, y1, x2, y2, r, fill_color, outline_color):
        for y in range(y1, y2 + 1):
            for x in range(x1, x2 + 1):
                if 0 <= x < WIDTH and 0 <= y < HEIGHT:
                    inside = False
                    if x1 + r <= x <= x2 - r and y1 <= y <= y2:
                        inside = True
                    elif x1 <= x <= x2 and y1 + r <= y <= y2 - r:
                        inside = True
                    else:
                        corners = [(x1+r,y1+r),(x2-r,y1+r),(x1+r,y2-r),(x2-r,y2-r)]
                        for cx, cy in corners:
                            dx, dy = x - cx, y - cy
                            if (x < x1+r or x > x2-r) and (y < y1+r or y > y2-r):
                                if dx*dx + dy*dy <= r*r:
                                    inside = True
                                    break
                    if inside:
                        on_edge = False
                        for nx, ny in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
                            if nx < x1 or nx > x2 or ny < y1 or ny > y2:
                                on_edge = True
                                break
                            if not on_edge:
                                for cx, cy in [(x1+r,y1+r),(x2-r,y1+r),(x1+r,y2-r),(x2-r,y2-r)]:
                                    dnx, dny = nx - cx, ny - cy
                                    if (nx < x1+r or nx > x2-r) and (ny < y1+r or ny > y2-r):
                                        if dnx*dnx + dny*dny > r*r:
                                            on_edge = True
                                            break
                        g[y][x] = outline_color if on_edge else fill_color

    fill_rounded_rect(g, 3, 2, 42, 33, 6, BLUE, BLACK)

    for row in range(34, 42):
        dy = row - 34
        x_start = max(8 - dy, 2)
        x_end = 14 - dy
        for x in range(x_start, x_end + 1):
            if 0 <= x < WIDTH:
                g[row][x] = BLUE
        if 0 <= x_start < WIDTH:
            g[row][x_start] = BLACK
        if 0 <= x_end < WIDTH and x_end != x_start:
            g[row][x_end] = BLACK
    if HEIGHT > 41:
        g[41][3] = BLACK
        g[41][4] = BLACK

    for y in range(4, 8):
        for x in range(6, 40):
            if g[y][x] == BLUE:
                g[y][x] = WHITE
                break
    for x in range(8, 38):
        if g[4][x] == BLUE:
            g[4][x] = WHITE

    A = [
        "  1111  ", " 111111 ", "111  111", "111  111", "111  111",
        "11111111", "11111111", "111  111", "111  111", "111  111", "111  111",
    ]
    I = [
        "11111111", "11111111", "   11   ", "   11   ", "   11   ",
        "   11   ", "   11   ", "   11   ", "   11   ", "11111111", "11111111",
    ]

    def draw_char(g, char_data, sx, sy, color):
        for dy, row in enumerate(char_data):
            for dx, ch in enumerate(row):
                if ch == '1':
                    x, y = sx + dx, sy + dy
                    if 0 <= x < WIDTH and 0 <= y < HEIGHT:
                        g[y][x] = color

    draw_char(g, A, 10, 11, WHITE)
    draw_char(g, I, 26, 11, WHITE)

    g[6][38] = WHITE; g[5][38] = WHITE; g[6][39] = WHITE
    g[7][38] = WHITE; g[6][37] = WHITE
    return g


def make_robot_grid():
    """Create sparkle pixel grid (mathematically generated)."""
    return make_sparkle_grid()


def make_selected_grid(g):
    """Create selected (pressed) state - swap white/blue."""
    g2 = [row[:] for row in g]
    for y in range(HEIGHT):
        for x in range(WIDTH):
            c = g2[y][x]
            if c == BLUE:
                g2[y][x] = WHITE
            elif c == WHITE:
                g2[y][x] = BLUE
    return g2


def grid_to_bitplanes(g):
    """Convert pixel grid to Amiga planar bitmap data."""
    words_per_row = WIDTH // 16
    plane0 = []
    plane1 = []

    for y in range(HEIGHT):
        for w in range(words_per_row):
            word0 = 0
            word1 = 0
            for bit in range(16):
                x = w * 16 + bit
                pen = g[y][x] if x < WIDTH else 0
                if pen & 1:
                    word0 |= (1 << (15 - bit))
                if pen & 2:
                    word1 |= (1 << (15 - bit))
            plane0.append(word0)
            plane1.append(word1)

    data = b''
    for w in plane0:
        data += struct.pack('>H', w)
    for w in plane1:
        data += struct.pack('>H', w)
    return data


def write_icon(filename, grid, sel_grid, stack_size=131072):
    """Write an Amiga .info file."""
    img1_data = grid_to_bitplanes(grid)
    img2_data = grid_to_bitplanes(sel_grid)

    gadget_flags = 0x0006  # GADGHIMAGE | GADGIMAGE

    with open(filename, 'wb') as f:
        # DiskObject header
        f.write(struct.pack('>HH', 0xE310, 1))

        # Gadget structure
        f.write(struct.pack('>I', 0))           # NextGadget
        f.write(struct.pack('>hh', 0, 0))       # LeftEdge, TopEdge
        f.write(struct.pack('>hh', WIDTH, HEIGHT))  # Width, Height
        f.write(struct.pack('>H', gadget_flags))
        f.write(struct.pack('>H', 1))           # Activation
        f.write(struct.pack('>H', 1))           # GadgetType
        f.write(struct.pack('>I', 1))           # GadgetRender (non-null)
        f.write(struct.pack('>I', 1))           # SelectRender (non-null)
        f.write(struct.pack('>I', 0))           # GadgetText
        f.write(struct.pack('>I', 0))           # MutualExclude
        f.write(struct.pack('>I', 0))           # SpecialInfo
        f.write(struct.pack('>H', 0))           # GadgetID
        f.write(struct.pack('>I', 0))           # UserData

        # DiskObject fields
        f.write(struct.pack('>BB', 1, 0))       # Type=WBTOOL, pad
        f.write(struct.pack('>I', 0))           # DefaultTool
        f.write(struct.pack('>I', 0))           # ToolTypes
        f.write(struct.pack('>II', 0x80000000, 0x80000000))  # CurrentX/Y
        f.write(struct.pack('>I', 0))           # DrawerData
        f.write(struct.pack('>I', 0))           # ToolWindow
        f.write(struct.pack('>I', stack_size))  # StackSize

        # Image 1 header
        f.write(struct.pack('>hh', 0, 0))
        f.write(struct.pack('>hh', WIDTH, HEIGHT))
        f.write(struct.pack('>h', DEPTH))
        f.write(struct.pack('>I', 0))           # ImageData placeholder
        f.write(struct.pack('>BB', 0x03, 0x00))
        f.write(struct.pack('>I', 0))

        # Image 1 data
        f.write(img1_data)

        # Image 2 header
        f.write(struct.pack('>hh', 0, 0))
        f.write(struct.pack('>hh', WIDTH, HEIGHT))
        f.write(struct.pack('>h', DEPTH))
        f.write(struct.pack('>I', 0))
        f.write(struct.pack('>BB', 0x03, 0x00))
        f.write(struct.pack('>I', 0))

        # Image 2 data
        f.write(img2_data)

    return os.path.getsize(filename)


def print_preview(g):
    """Print ASCII preview of the icon."""
    chars = ['.', '#', 'O', '@']
    for row in g:
        print(''.join(chars[p] for p in row))


if __name__ == '__main__':
    # Parse args
    args = sys.argv[1:]
    style = 'robot'
    outfile = None
    for a in args:
        if a == '--robot':
            style = 'robot'
        elif a == '--bubble':
            style = 'bubble'
        elif not a.startswith('-'):
            outfile = a

    if outfile is None:
        outfile = 'AmigaAI.info'

    print(f"Generating Amiga icon: {outfile} (style: {style})")
    print(f"  Size: {WIDTH}x{HEIGHT}, {DEPTH} bitplanes (4 colors)")

    if style == 'robot':
        grid = make_robot_grid()
    else:
        grid = make_bubble_grid()

    sel_grid = make_selected_grid(grid)

    print("\nNormal state:")
    print_preview(grid)

    size = write_icon(outfile, grid, sel_grid)
    print(f"\nWrote {size} bytes to {outfile}")
